services:
  python_base:
    build:
      context: ${REPO}
      dockerfile: Dockerfile
      args:
        MY_UID: ${MY_UID}
        MY_GID: ${MY_GID}
        MY_USER: ${MY_USER}
        MY_GROUP: ${MY_GROUP}
        PYTHON_V: ${PYTHON_V}
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    stdin_open: true
    tty: true